# Generated by Django 5.2.7 on 2025-10-06 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('driver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorWelcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('welcome_text', models.TextField(blank=True, default='Welcome to the Good Driver Incentive Program! We’re excited to have you onboard.')),
                ('sponsor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
