# Generated by Django 5.2.6 on 2025-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_drivernotification_sponsorwelcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
