# Generated by Django 5.2.6 on 2025-10-06 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0003_driverprofile_current_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
    ]
