# Generated by Django 4.2.25 on 2025-10-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0004_sponsorprofile_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivernotification',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='sponsorwelcome',
            name='sponsor_user',
        ),
        migrations.AddField(
            model_name='drivernotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='sponsorwelcome',
            name='sponsor_org',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcome_config', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='sponsorwelcome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
