# Generated by Django 4.2.25 on 2025-10-14 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_drivernotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='The username that was attempted.', max_length=254)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Additional info about the failure.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user account if the username matched an existing user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='users_faile_usernam_08fa4c_idx'), models.Index(fields=['created_at'], name='users_faile_created_debec3_idx')],
            },
        ),
    ]
