# Generated by Django 5.2.6 on 2025-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_failedloginattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="LockoutConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_failed_attempts", models.PositiveIntegerField(default=3)),
                ("lockout_cooldown_minutes", models.PositiveIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lockout Configuration",
                "verbose_name_plural": "Lockout Configuration",
            },
        ),
    ]
