# Generated by Django 5.2.6 on 2025-10-14 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_lockoutconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failedloginattempt",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="failedloginattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="failedloginattempt",
            name="username",
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
