# Generated by Django 5.2.7 on 2025-10-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_password_changed_at_passwordevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='notify_order_placed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='notify_points_change',
            field=models.BooleanField(default=True),
        ),
    ]
