# Generated by Django 5.2.6 on 2025-11-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_driverprofile_notify_order_placed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("points", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships",
                        to="users.driverprofile",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="users.sponsorprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("driver", "sponsor")},
            },
        ),
    ]
