# Generated by Django 5.2.7 on 2025-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_driversponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversponsor',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
