# Generated by Django 5.2.7 on 2025-11-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_driversponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversponsor',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DeletionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_user_id', models.IntegerField()),
                ('deleted_user_username', models.CharField(max_length=150)),
                ('deleted_user_role', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for deletion.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The user who performed the deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
