# Generated by Django 5.2.7 on 2025-11-16 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_driversponsor_approved_deletionauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversponsor',
            name='points',
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='points_expiration_days',
            field=models.PositiveIntegerField(default=90, help_text='Number of days points are valid for drivers'),
        ),
        migrations.CreateModel(
            name='DriverSponsorPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField()),
                ('driver_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to='users.driversponsor')),
            ],
        ),
    ]
