# Generated by Django 4.2.25 on 2025-11-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_driversponsor_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='notify_on_100_points',
            field=models.BooleanField(default=False, help_text='Notify me when any of my drivers reaches 100 points.'),
        ),
    ]
