# Generated by Django 5.2.7 on 2025-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_driversponsor_approved'),
        ('users', '0015_sponsorprofile_notify_on_100_points'),
    ]

    operations = [
    ]
