# Generated by Django 5.2.7 on 2025-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20251118_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
