# Generated by Django 5.2.7 on 2025-10-19 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverapplication',
            old_name='sponsor_org',
            new_name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='driverapplication',
            unique_together={('driver', 'organization')},
        ),
    ]
