# Generated by Django 5.2.7 on 2025-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='point_value_usd',
            field=models.DecimalField(decimal_places=4, default=0.01, help_text='Dollar value of a single point (ex: 0.01 = 1 point is worth $0.01)', max_digits=6),
        ),
    ]
