# Generated by Django 5.2.6 on 2025-10-21 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_catalogueitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogueitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('catalogue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalogue.catalogueitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='catalogue_i_viewed__ee45b8_idx')],
                'unique_together': {('user', 'catalogue_item')},
            },
        ),
    ]
