# Generated by Django 5.2.7 on 2025-10-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_catalogueitem_options_catalogueitem_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
