# Generated by Django 5.2.7 on 2025-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
