# Generated by Django 5.2.7 on 2025-11-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_order_orderitem'),
        ('users', '0012_driversponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='organization',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='users.sponsorprofile'),
        ),
    ]
