# Generated by Django 5.2.7 on 2025-11-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_remove_catalogue_organization_catalogue_sponsor'),
        ('users', '0012_driversponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='users.sponsorprofile'),
        ),
    ]
