# Generated by Django 5.2.7 on 2025-11-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_assign_default_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
