# Generated by Django 4.2.25 on 2025-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_knownloginlocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownloginlocations',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
