# Generated by Django 5.2.6 on 2025-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('idabout', models.AutoField(primary_key=True, serialize=False)),
                ('team_num', models.IntegerField()),
                ('version_number', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about',
                'managed': False,
            },
        ),
    ]
